# Generated by Django 4.1 on 2022-08-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=225)),
                ('No_of_courses', models.IntegerField()),
                ('Number_of_teacher', models.IntegerField()),
            ],
        ),
    ]
