# Generated by Django 4.1 on 2022-08-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_model2'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='Dob',
            field=models.CharField(default='2000', max_length=100),
        ),
    ]
