# Generated by Django 4.1 on 2022-08-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_delete_model1_delete_model2_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dob',
            field=models.DateTimeField(),
        ),
    ]
