# Generated by Django 4.1 on 2022-08-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dob',
            field=models.DateField(verbose_name='Y-M-D'),
        ),
    ]
