# Generated by Django 4.0.6 on 2022-08-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('Roll_Number', models.IntegerField()),
                ('Department_Name', models.CharField(max_length=225)),
                ('Courses_Name', models.CharField(max_length=225)),
                ('Semester_Number', models.IntegerField()),
            ],
        ),
    ]
