# Generated by Django 4.1 on 2022-08-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_model1_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=225)),
                ('No_of_courses', models.IntegerField()),
                ('Number_of_teacher', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('Dob', models.CharField(default='2000', max_length=100)),
                ('Roll_Number', models.IntegerField()),
                ('Department_Name', models.CharField(max_length=225)),
                ('Courses_Name', models.CharField(max_length=225)),
                ('Semester_Number', models.IntegerField()),
            ],
        ),
    ]
