# Generated by Django 4.1 on 2022-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_department_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1',
        ),
        migrations.DeleteModel(
            name='Model2',
        ),
        migrations.AddField(
            model_name='student',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='Department_Name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department_Name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Dob',
            field=models.CharField(default='2000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
